language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

install:
  - ./travis-init.sh
  - composer install -n

script:
  - ./vendor/bin/phpunit --coverage-text --exclude-group permissions
  - sudo ./vendor/bin/phpunit --coverage-text --group permissions
